<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;//consulta a la base de datos

class RegistrarDependenciasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dependencias = array("ABOGADO GENERAL","ARCHIVO HISTÓRICO UNIVERSITARIO","BACHILLERATO 5 DE MAYO","BUFETE JURÍDICO GRATUITO","CASA DEL JUBILADO","CENTRO DE DETECCIÓN BIOMOLECULAR","CENTRO DE EDUCACIÓN INTERNACIONAL","CENTRO UNIVERSITARIO DE PARTICIPACIÓN SOCIAL","CENTRO UNIVERSITARIO DE VINCULACIÓN","CENTRO UNIVERSITARIO PARA LA PREVENCIÓN DE DESASTRES REGIONALES","CIRCULO INFANTIL","COMPLEJO CULTURAL UNIVERSITARIO","COMPLEJO REGIONAL CENTRO","COMPLEJO REGIONAL MIXTECA","COMPLEJO REGIONAL NORORIENTAL","COMPLEJO REGIONAL NORTE","COMPLEJO REGIONAL SUR","CONTRALORÍA GENERAL","CONTRALORÍA SOCIAL","CONTROL VEHICULAR","COORDINACIÓN DE APOYOS INSTITUCIONALES","COORDINACIÓN DE BOLSA DE TRABAJO","COORDINACIÓN DE COMUNICACIÓN INSTITUCIONAL ","COORDINACIÓN DE DIFUSIÓN CULTURAL","COORDINACIÓN DE INFRAESTRUCTURA CIENTÍFICA Y EDUCATIVA","COORDINACIÓN DE PLANEACIÓN Y GESTIÓN","COORDINACIÓN DE PRODUCCIÓN CIENTÍFICA Y VISIBILIDAD INTERNACIONAL","COORDINACIÓN DEL CENTRO DE INVESTIGACIÓN SOBRE OPINIÓN PÚBLICA","COORDINACIÓN DEL PROGRAMA DE ESTUDIOS UNIVERSITARIOS","COORDINACIÓN GENERAL ADMINISTRATIVA","COORDINACIÓN GENERAL DE ASUNTOS ESTUDIANTILES","COORDINACIÓN GENERAL DE DESARROLLO SUSTENTABLE","DEFENSORÍA DE LOS DERECHOS UNIVERSITARIOS ","DEPARTAMENTO DE ADQUISICIONES, PROVEEDURÍA E INVENTARIOS","DEPARTAMENTO DE TRANSPORTE Y MOVILIDAD","DIRECCIÓN DE ACOMPAÑAMIENTO UNIVERSITARIO","DIRECCIÓN DE ADMINISTRACIÓN ESCOLAR","DIRECCIÓN DE APOYO Y SEGURIDAD UNIVERSITARIA","DIRECCIÓN DE CONTABILIDAD GENERAL","DIRECCIÓN DE CULTURA FÍSICA","DIRECCIÓN DE DIVULGACIÓN CIENTÍFICA","DIRECCIÓN DE EDUCACIÓN MEDIA SUPERIOR","DIRECCIÓN DE EDUCACIÓN SUPERIOR","DIRECCIÓN DE INFRAESTRUCTURA EDUCATIVA","DIRECCIÓN DE INNOVACIÓN Y TRANSFERENCIA DE CONOCIMIENTO","DIRECCIÓN DE INTERNACIONALIZACIÓN DE LA INVESTIGACIÓN","DIRECCIÓN DE MUSEOS UNIVERSITARIOS","DIRECCIÓN DE PATRIMONIO HISTÓRICO UNIVERSITARIO","DIRECCIÓN DE PLANEACIÓN Y PROYECTOS","DIRECCIÓN DE RECURSOS HUMANOS","DIRECCIÓN DE SERVICIO SOCIAL","DIRECCIÓN DE SERVICIOS GENERALES","DIRECCIÓN GENERAL DE BIBLIOTECAS","DIRECCIÓN GENERAL DE CÓMPUTO Y TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIONES","DIRECCIÓN GENERAL DE DESARROLLO INTERNACIONAL","DIRECCIÓN GENERAL DE EDUCACIÓN CONTINUA","DIRECCIÓN GENERAL DE ESTUDIOS DE POSGRADO","DIRECCIÓN GENERAL DE INVESTIGACIÓN","DIRECCIÓN GENERAL DE PUBLICACIONES","DIRECCIÓN DE ASEGURAMIENTO DE CALIDAD","DIRECCIÓN GENERAL DE CONTROL PATRIMONIAL","DIRECCIÓN GENERAL DE TECNOLOGÍA EDUCATIVA","ESCUELA DE ARTES PLÁSTICAS Y AUDIOVISUALES","FACULTAD DE ADMINISTRACIÓN","FACULTAD DE ARQUITECTURA","FACULTAD DE ARTES","FACULTAD DE CIENCIAS BIOLÓGICAS","FACULTAD DE CIENCIAS DE LA COMPUTACIÓN","FACULTAD DE CIENCIAS DE LA COMUNICACIÓN","FACULTAD DE CIENCIAS DE LA ELECTRÓNICA","FACULTAD DE CIENCIAS FÍSICO MATEMÁTICAS","FACULTAD DE CIENCIAS QUÍMICAS","FACULTAD DE CONTADURÍA PÚBLICA","FACULTAD DE CULTURA FÍSICA","FACULTAD DE DERECHO Y CIENCIAS SOCIALES","FACULTAD DE ECONOMÍA","FACULTAD DE ENFERMERÍA","FACULTAD DE ESTOMATOLOGÍA","FACULTAD DE FILOSOFÍA Y LETRAS","FACULTAD DE INGENIERÍA","FACULTAD DE INGENIERÍA AGROHIDRAULICA","FACULTAD DE INGENIERÍA QUÍMICA","FACULTAD DE LENGUAS","FACULTAD DE MEDICINA","FACULTAD DE MEDICINA VETERINARIA Y ZOOTECNIA","FACULTAD DE PSICOLOGÍA","FUNDACIÓN UNIVERSITARIA","HOSPITAL UNIVERSITARIO DE PUEBLA","HOSPITAL VETERINARIO PARA PEQUEÑAS ESPECIES","INSTITUTO DE CIENCIAS","INSTITUTO DE CIENCIAS DE GOBIERNO Y DESARROLLO ESTRATÉGICO","INSTITUTO DE CIENCIAS SOCIALES Y HUMANIDADES","INSTITUTO DE DE FÍSICA ING. LUIS RIVERA TERRAZAS","INSTITUTO DE FISIOLOGÍA","JARDÍN BOTÁNICO UNIVERSITARIO","PARQUE DEL AJEDREZ","PREPARATORIA 2 DE OCTUBRE","PREPARATORIA ALFONSO CALDERÓN MORENO","PREPARATORIA ENRIQUE CABRERA BARROSO REGIONAL TECAMACHALCO","PREPARATORIA ENRIQUE CABRERA BARROSO URBANA","PREPARATORIA GENERAL EMILIANO ZAPATA","PREPARATORIA GENERAL LÁZARO CÁRDENAS DEL RÍO","PREPARATORIA LIC. BENITO JUÁREZ GARCÍA","PREPARATORIA SIMÓN BOLÍVAR ATLIXCO","RECTORÍA","SECRETARÍA GENERAL","SECRETARÍA PARTICULAR DE RECTORÍA","TESORERÍA GENERAL","UNIDAD DE TRANSPARENCIA Y ACCESO A LA INFORMACIÓN","VICERRECTORÍA DE DOCENCIA","VICERRECTORÍA DE EXTENSIÓN Y DIFUSIÓN DE LA CULTURA","VICERRECTORÍA DE INVESTIGACIÓN Y ESTUDIOS DE POSGRADO");

    		foreach ($dependencias as $dependencia) {
    			DB::table('DP_DEPENDENCIAS')->insert([
		            'DEPENDENCIAS_NOM_DEPENDENCIA' => $dependencia,
		        ]);
    		}

        //
    }
}
