<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;//consulta a la base de datos

class RegistrarDependenciasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$dependencias = array("ABOGADO GENERAL","ARCHIVO HISTORICO REGIONAL UNIV.","BACHILLERATO 5 DE MAYO","BIOTERIO CLAUDE BERNAD","CENTRO DE DETECCION BIOMOLECULAR","CENTRO DE EDUCACION INTERNACIONAL","CENTRO DE INOV Y COMPETITIVIDAD EMP","CENTRO INNOVACION Y DISEÑO DIGIT","CENTRO UNIV. DE PART. SOCIAL","CENTRO UNIV.DE PREV.DESASTRES REG.","CENTRO UNIVERSITARIO DE SERVICIOS","CENTRO UNIVERSITARIO DE VINCULACION","CIRCULO INFANTIL","COMISIONADOS ADMINISTRATIVOS","COMISIONADOS DOCENTES","COMPLEJO CULTURAL UNIVERSITARIO","COMPLEJO REGIONAL CENTRO","COMPLEJO REGIONAL MIXTECA","COMPLEJO REGIONAL NORORIENTAL","COMPLEJO REGIONAL NORTE","COMPLEJO REGIONAL SUR","CONTRALORIA GENERAL","COORD.GRAL.DE DESARROLL SUSTENTABLE","COORDINACION DE GABINETE","COORDINACION GRAL. ADMINISTRATIVA","COORDINACION GRAL. DE ASUNTOS EST.","DEFENSORIA DE LOS DERECHOS UNIV.","DEPTO. DE ADQUISICIONES PROV. E INV.","DIR. ACOMPAÑAMIENTO UNIVERSITARIO","DIR. DE APOYO Y SEGURIDAD UNIVERSIT","DIR. DE INFRAESTRUCTURA EDUCATIVA","DIR. DE SERVICIOS AL ESTUDIANTE","DIR. GRAL DE INNOVACION EDUCATIVA","DIR. GRAL. DE CONTROL PATRIMONIAL","DIR. DE EST. DE POSG. AREA DE LA SALUD","DIR.GRAL DE COMPUTO Y T I Y COMUNIC.","DIRECCION DE ADMINISTRACION ESCOLAR","DIRECCION DE COMUNICACION","DIRECCION DE CONTABILIDAD GENERAL","DIRECCION DE CULTURA FISICA","DIRECCION DE DEPORTES DE COMBATE","DIRECCION DE RECURSOS HUMANOS","DIRECCION DE SERVICIOS GENERALES","DIRECCION GENERAL DE BIBLIOTECAS","DIRECCION GENERAL DE PLANEACION INS","DIRECCION GRAL. DE DESARROLLO INT.","ESC. DE ARTES PLASTICAS Y AUDIVIS.","ESC. PREP. 2 DE OCTUBRE","ESC. PREP. ALFONSO CALDERON MORENO","ESC. PREP. EMILIANO ZAPATA","ESC. PREP. ENRIQUE CABRERA B. PUEBLA","ESC. PREP. ENRIQUE CABRERA B. TEC.","ESC. PREP. GRAL. LAZARO CARDENAS DEL RIO","ESC. PREP. LIC. BENITO JUAREZ GARCIA","ESC. PREP.SIMON BOLIVAR DE ATLIXCO","FAC. DE CIENCIAS DE LA COMUNICACION","FAC. DE MEDICINA VETERINARIA Y ZOOT.","FACULTAD DE ADMINISTRACION","FACULTAD DE ARQUITECTURA","FACULTAD DE ARTES","FACULTAD DE CIENCIAS BIOLOGICAS","FACULTAD DE CIENCIAS QUIMICAS","FACULTAD DE CONTADURIA PUBLICA","FACULTAD DE CS.DE LA COMPUTACION","FACULTAD DE CS.DE LA ELECTRONICA","FACULTAD DE CS.FISICO MATEMATICAS","FACULTAD DE CULTURA FISICA","FACULTAD DE DERECHO Y CS.SOCIALES","FACULTAD DE ECONOMIA","FACULTAD DE ENFERMERIA","FACULTAD DE ESTOMATOLOGIA","FACULTAD DE FILOSOFIA","FACULTAD DE ING. AGROHIDRAULICA","FACULTAD DE INGENIERIA","FACULTAD DE INGENIERIA QUIMICA","FACULTAD DE LENGUAS","FACULTAD DE MEDICINA","FACULTAD DE PSICOLOGIA","FUNDACION UNIVERSITARIA","HERBARIO B.U.A.P.","HOSPITAL UNIVERSITARIO","INST.CS.DE GOBIERNO Y DES. ESTRAT","INST.DE CS.SOCIALES Y HUMANIDADES","INST.DE FISICA ING. LUIS RIVERA T.","INSTITUTO DE CIENCIAS","INSTITUTO DE FISIOLOGIA","NOMINA DE PENSIONADOS Y JUBILADOS","PREPARATORIA SECC. SAN MARTIN TEX.","RADIO BUAP","RECTORIA","REVISTA ELEMENTOS","SECRETARIA GENERAL","SECRETARIA PARTICULAR DE RECTORIA","TESORERIA GENERAL","UNIDAD ADMVA DE ACCESO A LA INFORMA","VICERRECTORIA DE DOCENCIA","VICERRECTORIA DE EXT. Y DIF.CULT.","VICERRECTORIA DE INV. Y EST. POSTG.");

    		foreach ($dependencias as $dependencia) {
    			DB::table('DP_DEPENDENCIAS')->insert([
		            'DEPENDENCIAS_NOM_DEPENDENCIA' => $dependencia,
		        ]);
    		}

        //
    }
}
